[package]
name = "yew_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.83"
yew = "0.19"
#js-sys = "0.3.60"
#web-sys = "0.3.60"
